REGIONS: dict[str, dict[str, str]] = {
    "11110": {"name_ko": "서울특별시 종로구", "name_en": "Seoul Jonglo-gu"},
    "11140": {"name_ko": "서울특별시 중구", "name_en": "Seoul Jung-gu"},
    "11170": {"name_ko": "서울특별시 용산구", "name_en": "Seoul Yongsan-gu"},
    "11200": {"name_ko": "서울특별시 성동구", "name_en": "Seoul Seongdong-gu"},
    "11215": {"name_ko": "서울특별시 광진구", "name_en": "Seoul Gwangjin-gu"},
    "11230": {"name_ko": "서울특별시 동대문구", "name_en": "Seoul Dongdaemun-gu"},
    "11260": {"name_ko": "서울특별시 중랑구", "name_en": "Seoul Junglang-gu"},
    "11290": {"name_ko": "서울특별시 성북구", "name_en": "Seoul Seongbug-gu"},
    "11305": {"name_ko": "서울특별시 강북구", "name_en": "Seoul Gangbug-gu"},
    "11320": {"name_ko": "서울특별시 도봉구", "name_en": "Seoul Dobong-gu"},
    "11350": {"name_ko": "서울특별시 노원구", "name_en": "Seoul Nowon-gu"},
    "11380": {"name_ko": "서울특별시 은평구", "name_en": "Seoul Eunpyeong-gu"},
    "11410": {"name_ko": "서울특별시 서대문구", "name_en": "Seoul Seodaemun-gu"},
    "11440": {"name_ko": "서울특별시 마포구", "name_en": "Seoul Mapo-gu"},
    "11470": {"name_ko": "서울특별시 양천구", "name_en": "Seoul Yangcheon-gu"},
    "11500": {"name_ko": "서울특별시 강서구", "name_en": "Seoul Gangseo-gu"},
    "11530": {"name_ko": "서울특별시 구로구", "name_en": "Seoul Gulo-gu"},
    "11545": {"name_ko": "서울특별시 금천구", "name_en": "Seoul Geumcheon-gu"},
    "11560": {"name_ko": "서울특별시 영등포구", "name_en": "Seoul Yeongdeungpo-gu"},
    "11590": {"name_ko": "서울특별시 동작구", "name_en": "Seoul Dongjag-gu"},
    "11620": {"name_ko": "서울특별시 관악구", "name_en": "Seoul Gwanag-gu"},
    "11650": {"name_ko": "서울특별시 서초구", "name_en": "Seoul Seocho-gu"},
    "11680": {"name_ko": "서울특별시 강남구", "name_en": "Seoul Gangnam-gu"},
    "11710": {"name_ko": "서울특별시 송파구", "name_en": "Seoul Songpa-gu"},
    "11740": {"name_ko": "서울특별시 강동구", "name_en": "Seoul Gangdong-gu"},
    "26110": {"name_ko": "부산광역시 중구", "name_en": "Busan Jung-gu"},
    "26140": {"name_ko": "부산광역시 서구", "name_en": "Busan Seo-gu"},
    "26170": {"name_ko": "부산광역시 동구", "name_en": "Busan Dong-gu"},
    "26200": {"name_ko": "부산광역시 영도구", "name_en": "Busan Yeongdo-gu"},
    "26230": {"name_ko": "부산광역시 부산진구", "name_en": "Busan Busanjin-gu"},
    "26260": {"name_ko": "부산광역시 동래구", "name_en": "Busan Donglae-gu"},
    "26290": {"name_ko": "부산광역시 남구", "name_en": "Busan Nam-gu"},
    "26320": {"name_ko": "부산광역시 북구", "name_en": "Busan Bug-gu"},
    "26350": {"name_ko": "부산광역시 해운대구", "name_en": "Busan Haeundae-gu"},
    "26380": {"name_ko": "부산광역시 사하구", "name_en": "Busan Saha-gu"},
    "26410": {"name_ko": "부산광역시 금정구", "name_en": "Busan Geumjeong-gu"},
    "26440": {"name_ko": "부산광역시 강서구", "name_en": "Busan Gangseo-gu"},
    "26470": {"name_ko": "부산광역시 연제구", "name_en": "Busan Yeonje-gu"},
    "26500": {"name_ko": "부산광역시 수영구", "name_en": "Busan Suyeong-gu"},
    "26530": {"name_ko": "부산광역시 사상구", "name_en": "Busan Sasang-gu"},
    "26710": {"name_ko": "부산광역시 기장군", "name_en": "Busan Gijang-gun"},
    "27110": {"name_ko": "대구광역시 중구", "name_en": "Daegu Jung-gu"},
    "27140": {"name_ko": "대구광역시 동구", "name_en": "Daegu Dong-gu"},
    "27170": {"name_ko": "대구광역시 서구", "name_en": "Daegu Seo-gu"},
    "27200": {"name_ko": "대구광역시 남구", "name_en": "Daegu Nam-gu"},
    "27230": {"name_ko": "대구광역시 북구", "name_en": "Daegu Bug-gu"},
    "27260": {"name_ko": "대구광역시 수성구", "name_en": "Daegu Suseong-gu"},
    "27290": {"name_ko": "대구광역시 달서구", "name_en": "Daegu Dalseo-gu"},
    "27710": {"name_ko": "대구광역시 달성군", "name_en": "Daegu Dalseong-gun"},
    "28110": {"name_ko": "인천광역시 중구", "name_en": "Incheon Jung-gu"},
    "28140": {"name_ko": "인천광역시 동구", "name_en": "Incheon Dong-gu"},
    "28170": {"name_ko": "인천광역시 남구", "name_en": "Incheon Nam-gu"},
    "28185": {"name_ko": "인천광역시 연수구", "name_en": "Incheon Yeonsu-gu"},
    "28200": {"name_ko": "인천광역시 남동구", "name_en": "Incheon Namdong-gu"},
    "28237": {"name_ko": "인천광역시 부평구", "name_en": "Incheon Bupyeong-gu"},
    "28245": {"name_ko": "인천광역시 계양구", "name_en": "Incheon Gyeyang-gu"},
    "28260": {"name_ko": "인천광역시 서구", "name_en": "Incheon Seo-gu"},
    "28710": {"name_ko": "인천광역시 강화군", "name_en": "Incheon Ganghwa-gun"},
    "28720": {"name_ko": "인천광역시 옹진군", "name_en": "Incheon Ongjin-gun"},
    "29110": {"name_ko": "광주광역시 동구", "name_en": "Gwangju Dong-gu"},
    "29140": {"name_ko": "광주광역시 서구", "name_en": "Gwangju Seo-gu"},
    "29155": {"name_ko": "광주광역시 남구", "name_en": "Gwangju Nam-gu"},
    "29170": {"name_ko": "광주광역시 북구", "name_en": "Gwangju Bug-gu"},
    "29200": {"name_ko": "광주광역시 광산구", "name_en": "Gwangju Gwangsan-gu"},
    "30110": {"name_ko": "대전광역시 동구", "name_en": "Daejeon Dong-gu"},
    "30140": {"name_ko": "대전광역시 중구", "name_en": "Daejeon Jung-gu"},
    "30170": {"name_ko": "대전광역시 서구", "name_en": "Daejeon Seo-gu"},
    "30200": {"name_ko": "대전광역시 유성구", "name_en": "Daejeon Yuseong-gu"},
    "30230": {"name_ko": "대전광역시 대덕구", "name_en": "Daejeon Daedeog-gu"},
    "31110": {"name_ko": "울산광역시 중구", "name_en": "Ulsan Jung-gu"},
    "31140": {"name_ko": "울산광역시 남구", "name_en": "Ulsan Nam-gu"},
    "31170": {"name_ko": "울산광역시 동구", "name_en": "Ulsan Dong-gu"},
    "31200": {"name_ko": "울산광역시 북구", "name_en": "Ulsan Bug-gu"},
    "31710": {"name_ko": "울산광역시 울주군", "name_en": "Ulsan Ulju-gun"},
    "36110": {"name_ko": "세종특별자치시", "name_en": "Sejong"},
    "41110": {"name_ko": "경기도 수원시", "name_en": "Gyeonggi-do Suwon-si"},
    "41111": {"name_ko": "경기도 수원시 장안구", "name_en": "Gyeonggi-do Suwon-si Jangan-gu"},
    "41113": {"name_ko": "경기도 수원시 권선구", "name_en": "Gyeonggi-do Suwon-si Gwonseon-gu"},
    "41115": {"name_ko": "경기도 수원시 팔달구", "name_en": "Gyeonggi-do Suwon-si Paldal-gu"},
    "41117": {"name_ko": "경기도 수원시 영통구", "name_en": "Gyeonggi-do Suwon-si Yeongtong-gu"},
    "41130": {"name_ko": "경기도 성남시", "name_en": "Gyeonggi-do Seongnam-si"},
    "41131": {"name_ko": "경기도 성남시 수정구", "name_en": "Gyeonggi-do Seongnam-si Sujeong-gu"},
    "41133": {"name_ko": "경기도 성남시 중원구", "name_en": "Gyeonggi-do Seongnam-si Jungwon-gu"},
    "41135": {"name_ko": "경기도 성남시 분당구", "name_en": "Gyeonggi-do Seongnam-si Bundang-gu"},
    "41150": {"name_ko": "경기도 의정부시", "name_en": "Gyeonggi-do Uijeongbu-si"},
    "41170": {"name_ko": "경기도 안양시", "name_en": "Gyeonggi-do Anyang-si"},
    "41171": {"name_ko": "경기도 안양시 만안구", "name_en": "Gyeonggi-do Anyang-si Manan-gu"},
    "41173": {"name_ko": "경기도 안양시 동안구", "name_en": "Gyeonggi-do Anyang-si Dongan-gu"},
    "41190": {"name_ko": "경기도 부천시", "name_en": "Gyeonggi-do Bucheon-si"},
    "41210": {"name_ko": "경기도 광명시", "name_en": "Gyeonggi-do Gwangmyeong-si"},
    "41220": {"name_ko": "경기도 평택시", "name_en": "Gyeonggi-do Pyeongtaeg-si"},
    "41250": {"name_ko": "경기도 동두천시", "name_en": "Gyeonggi-do Dongducheon-si"},
    "41270": {"name_ko": "경기도 안산시", "name_en": "Gyeonggi-do Ansan-si"},
    "41271": {"name_ko": "경기도 안산시 상록구", "name_en": "Gyeonggi-do Ansan-si Sanglog-gu"},
    "41273": {"name_ko": "경기도 안산시 단원구", "name_en": "Gyeonggi-do Ansan-si Danwon-gu"},
    "41280": {"name_ko": "경기도 고양시", "name_en": "Gyeonggi-do Goyang-si"},
    "41281": {"name_ko": "경기도 고양시 덕양구", "name_en": "Gyeonggi-do Goyang-si Deogyang-gu"},
    "41285": {"name_ko": "경기도 고양시 일산동구", "name_en": "Gyeonggi-do Goyang-si Ilsandong-gu"},
    "41287": {"name_ko": "경기도 고양시 일산서구", "name_en": "Gyeonggi-do Goyang-si Ilsanseo-gu"},
    "41290": {"name_ko": "경기도 과천시", "name_en": "Gyeonggi-do Gwacheon-si"},
    "41310": {"name_ko": "경기도 구리시", "name_en": "Gyeonggi-do Guli-si"},
    "41360": {"name_ko": "경기도 남양주시", "name_en": "Gyeonggi-do Namyangju-si"},
    "41370": {"name_ko": "경기도 오산시", "name_en": "Gyeonggi-do Osan-si"},
    "41390": {"name_ko": "경기도 시흥시", "name_en": "Gyeonggi-do Siheung-si"},
    "41410": {"name_ko": "경기도 군포시", "name_en": "Gyeonggi-do Gunpo-si"},
    "41430": {"name_ko": "경기도 의왕시", "name_en": "Gyeonggi-do Uiwang-si"},
    "41450": {"name_ko": "경기도 하남시", "name_en": "Gyeonggi-do Hanam-si"},
    "41460": {"name_ko": "경기도 용인시", "name_en": "Gyeonggi-do Yongin-si"},
    "41461": {"name_ko": "경기도 용인시 처인구", "name_en": "Gyeonggi-do Yongin-si Cheoin-gu"},
    "41463": {"name_ko": "경기도 용인시 기흥구", "name_en": "Gyeonggi-do Yongin-si Giheung-gu"},
    "41465": {"name_ko": "경기도 용인시 수지구", "name_en": "Gyeonggi-do Yongin-si Suji-gu"},
    "41480": {"name_ko": "경기도 파주시", "name_en": "Gyeonggi-do Paju-si"},
    "41500": {"name_ko": "경기도 이천시", "name_en": "Gyeonggi-do Icheon-si"},
    "41550": {"name_ko": "경기도 안성시", "name_en": "Gyeonggi-do Anseong-si"},
    "41570": {"name_ko": "경기도 김포시", "name_en": "Gyeonggi-do Gimpo-si"},
    "41590": {"name_ko": "경기도 화성시", "name_en": "Gyeonggi-do Hwaseong-si"},
    "41610": {"name_ko": "경기도 광주시", "name_en": "Gyeonggi-do Gwangju-si"},
    "41630": {"name_ko": "경기도 양주시", "name_en": "Gyeonggi-do Yangju-si"},
    "41650": {"name_ko": "경기도 포천시", "name_en": "Gyeonggi-do Pocheon-si"},
    "41670": {"name_ko": "경기도 여주시", "name_en": "Gyeonggi-do Yeoju-si"},
    "41800": {"name_ko": "경기도 연천군", "name_en": "Gyeonggi-do Yeoncheon-gun"},
    "41820": {"name_ko": "경기도 가평군", "name_en": "Gyeonggi-do Gapyeong-gun"},
    "41830": {"name_ko": "경기도 양평군", "name_en": "Gyeonggi-do Yangpyeong-gun"},
    "42110": {"name_ko": "강원도 춘천시", "name_en": "Gangwon-do Chuncheon-si"},
    "42130": {"name_ko": "강원도 원주시", "name_en": "Gangwon-do Wonju-si"},
    "42150": {"name_ko": "강원도 강릉시", "name_en": "Gangwon-do Gangleung-si"},
    "42170": {"name_ko": "강원도 동해시", "name_en": "Gangwon-do Donghae-si"},
    "42190": {"name_ko": "강원도 태백시", "name_en": "Gangwon-do Taebaeg-si"},
    "42210": {"name_ko": "강원도 속초시", "name_en": "Gangwon-do Sogcho-si"},
    "42230": {"name_ko": "강원도 삼척시", "name_en": "Gangwon-do Samcheog-si"},
    "42720": {"name_ko": "강원도 홍천군", "name_en": "Gangwon-do Hongcheon-gun"},
    "42730": {"name_ko": "강원도 횡성군", "name_en": "Gangwon-do Hoengseong-gun"},
    "42750": {"name_ko": "강원도 영월군", "name_en": "Gangwon-do Yeongwol-gun"},
    "42760": {"name_ko": "강원도 평창군", "name_en": "Gangwon-do Pyeongchang-gun"},
    "42770": {"name_ko": "강원도 정선군", "name_en": "Gangwon-do Jeongseon-gun"},
    "42780": {"name_ko": "강원도 철원군", "name_en": "Gangwon-do Cheolwon-gun"},
    "42790": {"name_ko": "강원도 화천군", "name_en": "Gangwon-do Hwacheon-gun"},
    "42800": {"name_ko": "강원도 양구군", "name_en": "Gangwon-do Yanggu-gun"},
    "42810": {"name_ko": "강원도 인제군", "name_en": "Gangwon-do Inje-gun"},
    "42820": {"name_ko": "강원도 고성군", "name_en": "Gangwon-do Goseong-gun"},
    "42830": {"name_ko": "강원도 양양군", "name_en": "Gangwon-do Yangyang-gun"},
    "43110": {"name_ko": "충청북도 청주시", "name_en": "Chungcheongbuk-do Cheongju-si"},
    "43111": {"name_ko": "충청북도 청주시 상당구", "name_en": "Chungcheongbuk-do Cheongju-si Sangdang-gu"},
    "43112": {"name_ko": "충청북도 청주시 서원구", "name_en": "Chungcheongbuk-do Cheongju-si Seowon-gu"},
    "43113": {"name_ko": "충청북도 청주시 흥덕구", "name_en": "Chungcheongbuk-do Cheongju-si Heungdeog-gu"},
    "43114": {"name_ko": "충청북도 청주시 청원구", "name_en": "Chungcheongbuk-do Cheongju-si Cheongwon-gu"},
    "43130": {"name_ko": "충청북도 충주시", "name_en": "Chungcheongbuk-do Chungju-si"},
    "43150": {"name_ko": "충청북도 제천시", "name_en": "Chungcheongbuk-do Jecheon-si"},
    "43720": {"name_ko": "충청북도 보은군", "name_en": "Chungcheongbuk-do Boeun-gun"},
    "43730": {"name_ko": "충청북도 옥천군", "name_en": "Chungcheongbuk-do Ogcheon-gun"},
    "43740": {"name_ko": "충청북도 영동군", "name_en": "Chungcheongbuk-do Yeongdong-gun"},
    "43745": {"name_ko": "충청북도 증평군", "name_en": "Chungcheongbuk-do Jeungpyeong-gun"},
    "43750": {"name_ko": "충청북도 진천군", "name_en": "Chungcheongbuk-do Jincheon-gun"},
    "43760": {"name_ko": "충청북도 괴산군", "name_en": "Chungcheongbuk-do Goesan-gun"},
    "43770": {"name_ko": "충청북도 음성군", "name_en": "Chungcheongbuk-do Eumseong-gun"},
    "43800": {"name_ko": "충청북도 단양군", "name_en": "Chungcheongbuk-do Danyang-gun"},
    "44130": {"name_ko": "충청남도 천안시", "name_en": "Chungcheongnam-do Cheonan-si"},
    "44131": {"name_ko": "충청남도 천안시 동남구", "name_en": "Chungcheongnam-do Cheonan-si Dongnam-gu"},
    "44133": {"name_ko": "충청남도 천안시 서북구", "name_en": "Chungcheongnam-do Cheonan-si Seobug-gu"},
    "44150": {"name_ko": "충청남도 공주시", "name_en": "Chungcheongnam-do Gongju-si"},
    "44180": {"name_ko": "충청남도 보령시", "name_en": "Chungcheongnam-do Bolyeong-si"},
    "44200": {"name_ko": "충청남도 아산시", "name_en": "Chungcheongnam-do Asan-si"},
    "44210": {"name_ko": "충청남도 서산시", "name_en": "Chungcheongnam-do Seosan-si"},
    "44230": {"name_ko": "충청남도 논산시", "name_en": "Chungcheongnam-do Nonsan-si"},
    "44250": {"name_ko": "충청남도 계룡시", "name_en": "Chungcheongnam-do Gyelyong-si"},
    "44270": {"name_ko": "충청남도 당진시", "name_en": "Chungcheongnam-do Dangjin-si"},
    "44710": {"name_ko": "충청남도 금산군", "name_en": "Chungcheongnam-do Geumsan-gun"},
    "44760": {"name_ko": "충청남도 부여군", "name_en": "Chungcheongnam-do Buyeo-gun"},
    "44770": {"name_ko": "충청남도 서천군", "name_en": "Chungcheongnam-do Seocheon-gun"},
    "44790": {"name_ko": "충청남도 청양군", "name_en": "Chungcheongnam-do Cheongyang-gun"},
    "44800": {"name_ko": "충청남도 홍성군", "name_en": "Chungcheongnam-do Hongseong-gun"},
    "44810": {"name_ko": "충청남도 예산군", "name_en": "Chungcheongnam-do Yesan-gun"},
    "44825": {"name_ko": "충청남도 태안군", "name_en": "Chungcheongnam-do Taean-gun"},
    "45110": {"name_ko": "전라북도 전주시", "name_en": "Jeollabuk-do Jeonju-si"},
    "45111": {"name_ko": "전라북도 전주시 완산구", "name_en": "Jeollabuk-do Jeonju-si Wansan-gu"},
    "45113": {"name_ko": "전라북도 전주시 덕진구", "name_en": "Jeollabuk-do Jeonju-si Deogjin-gu"},
    "45130": {"name_ko": "전라북도 군산시", "name_en": "Jeollabuk-do Gunsan-si"},
    "45140": {"name_ko": "전라북도 익산시", "name_en": "Jeollabuk-do Igsan-si"},
    "45180": {"name_ko": "전라북도 정읍시", "name_en": "Jeollabuk-do Jeongeub-si"},
    "45190": {"name_ko": "전라북도 남원시", "name_en": "Jeollabuk-do Namwon-si"},
    "45210": {"name_ko": "전라북도 김제시", "name_en": "Jeollabuk-do Gimje-si"},
    "45710": {"name_ko": "전라북도 완주군", "name_en": "Jeollabuk-do Wanju-gun"},
    "45720": {"name_ko": "전라북도 진안군", "name_en": "Jeollabuk-do Jinan-gun"},
    "45730": {"name_ko": "전라북도 무주군", "name_en": "Jeollabuk-do Muju-gun"},
    "45740": {"name_ko": "전라북도 장수군", "name_en": "Jeollabuk-do Jangsu-gun"},
    "45750": {"name_ko": "전라북도 임실군", "name_en": "Jeollabuk-do Imsil-gun"},
    "45770": {"name_ko": "전라북도 순창군", "name_en": "Jeollabuk-do Sunchang-gun"},
    "45790": {"name_ko": "전라북도 고창군", "name_en": "Jeollabuk-do Gochang-gun"},
    "45800": {"name_ko": "전라북도 부안군", "name_en": "Jeollabuk-do Buan-gun"},
    "46110": {"name_ko": "전라남도 목포시", "name_en": "Jeollanam-do Mogpo-si"},
    "46130": {"name_ko": "전라남도 여수시", "name_en": "Jeollanam-do Yeosu-si"},
    "46150": {"name_ko": "전라남도 순천시", "name_en": "Jeollanam-do Suncheon-si"},
    "46170": {"name_ko": "전라남도 나주시", "name_en": "Jeollanam-do Naju-si"},
    "46230": {"name_ko": "전라남도 광양시", "name_en": "Jeollanam-do Gwangyang-si"},
    "46710": {"name_ko": "전라남도 담양군", "name_en": "Jeollanam-do Damyang-gun"},
    "46720": {"name_ko": "전라남도 곡성군", "name_en": "Jeollanam-do Gogseong-gun"},
    "46730": {"name_ko": "전라남도 구례군", "name_en": "Jeollanam-do Gulye-gun"},
    "46770": {"name_ko": "전라남도 고흥군", "name_en": "Jeollanam-do Goheung-gun"},
    "46780": {"name_ko": "전라남도 보성군", "name_en": "Jeollanam-do Boseong-gun"},
    "46790": {"name_ko": "전라남도 화순군", "name_en": "Jeollanam-do Hwasun-gun"},
    "46800": {"name_ko": "전라남도 장흥군", "name_en": "Jeollanam-do Jangheung-gun"},
    "46810": {"name_ko": "전라남도 강진군", "name_en": "Jeollanam-do Gangjin-gun"},
    "46820": {"name_ko": "전라남도 해남군", "name_en": "Jeollanam-do Haenam-gun"},
    "46830": {"name_ko": "전라남도 영암군", "name_en": "Jeollanam-do Yeongam-gun"},
    "46840": {"name_ko": "전라남도 무안군", "name_en": "Jeollanam-do Muan-gun"},
    "46860": {"name_ko": "전라남도 함평군", "name_en": "Jeollanam-do Hampyeong-gun"},
    "46870": {"name_ko": "전라남도 영광군", "name_en": "Jeollanam-do Yeonggwang-gun"},
    "46880": {"name_ko": "전라남도 장성군", "name_en": "Jeollanam-do Jangseong-gun"},
    "46890": {"name_ko": "전라남도 완도군", "name_en": "Jeollanam-do Wando-gun"},
    "46900": {"name_ko": "전라남도 진도군", "name_en": "Jeollanam-do Jindo-gun"},
    "46910": {"name_ko": "전라남도 신안군", "name_en": "Jeollanam-do Sinan-gun"},
    "47110": {"name_ko": "경상북도 포항시", "name_en": "Gyeongsangbuk-do Pohang-si"},
    "47111": {"name_ko": "경상북도 포항시 남구", "name_en": "Gyeongsangbuk-do Pohang-si Nam-gu"},
    "47113": {"name_ko": "경상북도 포항시 북구", "name_en": "Gyeongsangbuk-do Pohang-si Bug-gu"},
    "47130": {"name_ko": "경상북도 경주시", "name_en": "Gyeongsangbuk-do Gyeongju-si"},
    "47150": {"name_ko": "경상북도 김천시", "name_en": "Gyeongsangbuk-do Gimcheon-si"},
    "47170": {"name_ko": "경상북도 안동시", "name_en": "Gyeongsangbuk-do Andong-si"},
    "47190": {"name_ko": "경상북도 구미시", "name_en": "Gyeongsangbuk-do Gumi-si"},
    "47210": {"name_ko": "경상북도 영주시", "name_en": "Gyeongsangbuk-do Yeongju-si"},
    "47230": {"name_ko": "경상북도 영천시", "name_en": "Gyeongsangbuk-do Yeongcheon-si"},
    "47250": {"name_ko": "경상북도 상주시", "name_en": "Gyeongsangbuk-do Sangju-si"},
    "47280": {"name_ko": "경상북도 문경시", "name_en": "Gyeongsangbuk-do Mungyeong-si"},
    "47290": {"name_ko": "경상북도 경산시", "name_en": "Gyeongsangbuk-do Gyeongsan-si"},
    "47720": {"name_ko": "경상북도 군위군", "name_en": "Gyeongsangbuk-do Gunwi-gun"},
    "47730": {"name_ko": "경상북도 의성군", "name_en": "Gyeongsangbuk-do Uiseong-gun"},
    "47750": {"name_ko": "경상북도 청송군", "name_en": "Gyeongsangbuk-do Cheongsong-gun"},
    "47760": {"name_ko": "경상북도 영양군", "name_en": "Gyeongsangbuk-do Yeongyang-gun"},
    "47770": {"name_ko": "경상북도 영덕군", "name_en": "Gyeongsangbuk-do Yeongdeog-gun"},
    "47820": {"name_ko": "경상북도 청도군", "name_en": "Gyeongsangbuk-do Cheongdo-gun"},
    "47830": {"name_ko": "경상북도 고령군", "name_en": "Gyeongsangbuk-do Golyeong-gun"},
    "47840": {"name_ko": "경상북도 성주군", "name_en": "Gyeongsangbuk-do Seongju-gun"},
    "47850": {"name_ko": "경상북도 칠곡군", "name_en": "Gyeongsangbuk-do Chilgog-gun"},
    "47900": {"name_ko": "경상북도 예천군", "name_en": "Gyeongsangbuk-do Yecheon-gun"},
    "47920": {"name_ko": "경상북도 봉화군", "name_en": "Gyeongsangbuk-do Bonghwa-gun"},
    "47930": {"name_ko": "경상북도 울진군", "name_en": "Gyeongsangbuk-do Uljin-gun"},
    "47940": {"name_ko": "경상북도 울릉군", "name_en": "Gyeongsangbuk-do Ulleung-gun"},
    "48120": {"name_ko": "경상남도 창원시", "name_en": "Gyeongsangnam-do Changwon-si"},
    "48121": {"name_ko": "경상남도 창원시 의창구", "name_en": "Gyeongsangnam-do Changwon-si Uichang-gu"},
    "48123": {"name_ko": "경상남도 창원시 성산구", "name_en": "Gyeongsangnam-do Changwon-si Seongsan-gu"},
    "48125": {"name_ko": "경상남도 창원시 마산합포구", "name_en": "Gyeongsangnam-do Changwon-si Masanhabpo-gu"},
    "48127": {"name_ko": "경상남도 창원시 마산회원구", "name_en": "Gyeongsangnam-do Changwon-si Masanhoewon-gu"},
    "48129": {"name_ko": "경상남도 창원시 진해구", "name_en": "Gyeongsangnam-do Changwon-si Jinhae-gu"},
    "48170": {"name_ko": "경상남도 진주시", "name_en": "Gyeongsangnam-do Jinju-si"},
    "48220": {"name_ko": "경상남도 통영시", "name_en": "Gyeongsangnam-do Tongyeong-si"},
    "48240": {"name_ko": "경상남도 사천시", "name_en": "Gyeongsangnam-do Sacheon-si"},
    "48250": {"name_ko": "경상남도 김해시", "name_en": "Gyeongsangnam-do Gimhae-si"},
    "48270": {"name_ko": "경상남도 밀양시", "name_en": "Gyeongsangnam-do Milyang-si"},
    "48310": {"name_ko": "경상남도 거제시", "name_en": "Gyeongsangnam-do Geoje-si"},
    "48330": {"name_ko": "경상남도 양산시", "name_en": "Gyeongsangnam-do Yangsan-si"},
    "48720": {"name_ko": "경상남도 의령군", "name_en": "Gyeongsangnam-do Uilyeong-gun"},
    "48730": {"name_ko": "경상남도 함안군", "name_en": "Gyeongsangnam-do Haman-gun"},
    "48740": {"name_ko": "경상남도 창녕군", "name_en": "Gyeongsangnam-do Changnyeong-gun"},
    "48820": {"name_ko": "경상남도 고성군", "name_en": "Gyeongsangnam-do Goseong-gun"},
    "48840": {"name_ko": "경상남도 남해군", "name_en": "Gyeongsangnam-do Namhae-gun"},
    "48850": {"name_ko": "경상남도 하동군", "name_en": "Gyeongsangnam-do Hadong-gun"},
    "48860": {"name_ko": "경상남도 산청군", "name_en": "Gyeongsangnam-do Sancheong-gun"},
    "48870": {"name_ko": "경상남도 함양군", "name_en": "Gyeongsangnam-do Hamyang-gun"},
    "48880": {"name_ko": "경상남도 거창군", "name_en": "Gyeongsangnam-do Geochang-gun"},
    "48890": {"name_ko": "경상남도 합천군", "name_en": "Gyeongsangnam-do Habcheon-gun"},
    "50110": {"name_ko": "제주특별자치도 제주시", "name_en": "Jeju-do Jeju-si"},
    "50130": {"name_ko": "제주특별자치도 서귀포시", "name_en": "Jeju-do Seogwipo-si"},
}


def is_valid_region(code: str) -> bool:
    return code in REGIONS
